INSERT INTO Data (ID, Name, Age) VALUES (/*1*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (vw_alunos_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso_nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_curso, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso.id_curso;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*2*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_alunos_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*3*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (alunos_status_matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.status, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_disciplina;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*4*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professores_turmas, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.horario, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.id_professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.id_professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_disciplina;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*5*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (alunos_maiores_20, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.data_nascimento, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (data_nasc_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (YEAR(CURRENT_DATE), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (YEAR(aluno.data_nascimento), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (>, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (20;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*6*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplinas_carga_horaria_curso, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso.carga_horaria, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso.id_curso, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_curso;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*7*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professores_especialidades, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.especialidade, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (especialidade_professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.id_professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.id_professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_disciplina;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*8*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (alunos_multidisciplinas, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (COUNT(disciplina.id_disciplina), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (qtd_disciplinas, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (GROUP, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (HAVING, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (COUNT(disciplina.id_disciplina), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (>, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (1;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*9*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (alunos_disciplinas_concluidas, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina_nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.status, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('Concluído';, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*10*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turmas_semestre, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.id_turma, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.semestre, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.horario, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.semestre, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('2024.1';, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*11*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (alunos_matriculas_trancadas, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.status, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('Trancado';, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*12*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplinas_sem_alunos, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina_nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (LEFT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (IS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (NULL;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*13*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (alunos_status, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.status, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*14*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_professores_especialidade, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.especialidade, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.id_professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.id_professor;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*15*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (lista_alunos_idades, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.data_nascimento, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (data_nasc_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*16*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (alunos_ultimas_matriculas, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MAX(matricula.data_matricula), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula_data, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (GROUP, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*17*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplinas_curso_especifico, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso_nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_curso, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso.id_curso, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (curso.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('Engenharia, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (de, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Software';, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*18*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professores_sem_turmas, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor_nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (LEFT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.id_professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.id_professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.id_turma, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (IS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (NULL;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*19*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (lista_alunos_cpf_email, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.cpf, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_cpf, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.email, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno_email, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (aluno.id_aluno, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (matricula.id_aluno;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (/*20*/, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_disciplinas_professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor_nome, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina_nome, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (professor.id_professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.id_professor, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INNER, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (JOIN, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (turma.id_disciplina, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (=, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (disciplina.id_disciplina;, 'undefined', undefined);